config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("sushi.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include('sushi.urls', namespace='sushi')),
]

sushi/urls.py
from django.urls import path
from . import views
from .views import SignUpView
from sushi import views

app_name = 'sushi'
urlpatterns = [


    path('', views.product_list, name='product_list'),
    path('category/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/', views.product_detail, name='product_detail'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('orders/create/', views.order_create, name='order_create'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

sushi/models.py
# Create your models here.
from datetime import datetime

from django.contrib.auth.models import User, AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def get_absolute_url(self):
        return reverse('sushi:product_list_by_category', args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('sushi:product_detail', args=[self.id],)

    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'),)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)


class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    table_number = models.IntegerField()
    products = models.ManyToManyField(Product, through='OrderItem')
    delivered = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"Order {self.id}"

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        return self.price * self.quantity

sushi/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Order


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = (
            'username',
            'email',
            'age',
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            'username',
            'email',
            'age',
        )


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput,
    )


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['table_number']

sushi/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, TemplateView, DetailView, ListView, UpdateView, DeleteView
from .forms import CustomUserCreationForm, CartAddProductForm, OrderCreateForm
from .models import Product, Category, Cart, OrderItem
from .cart import Cart


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'product-list.html', {
        'category': category,
        'categories': categories,
        'products': products,
    })


def product_detail(request, id):
    product = get_object_or_404(Product, id=id,  available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'product_detail.html', {
        'product': product,
        'cart_product_form': cart_product_form,
    })


@require_POST
def cart_add(request, product_id):
    if request.user.is_authenticated:

        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
                     quantity=cd['quantity'],
                     override_quantity=cd['override'])
        return redirect('sushi:cart_detail')
    else:
        return HttpResponse("Log in to continue")


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('sushi:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'cart_detail.html', {'cart': cart})


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,

                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'],

                                         )
                cart.clear()

            return render(request, 'order_created.html', {
                                'order': order,
                            })
    else:
        form = OrderCreateForm()
    return render(request, 'order_create.html', {
                        'cart': cart,
                        'form': form,
                    })


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MySushi{% block title %}{% endblock %}</title>

    {% block styles %}
        <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">
    {% endblock %}

    {% block scripts %}
        <script src="{% static './js/bootstrap.min.js' %}" async defer></script>
    {% endblock %}
</head>
<body>

{% include './partials/_menu.html' %}


<div class="container">
    <div class="row">
        <div class="col">
            {% block content %}



            {% endblock content %}
        </div>
    </div>
</div>


</body>
</html>

templates/cart.html
{% extends 'menu.html' %}

{% block title %}Cart{% endblock %}


{% block content %}

<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">Cart</h3>
        </div>
        <div class="col d-flex justify-content-end mb-2 noPadding">
        </div>
    </div>
    <div class="schedules-content">
        <table class="table border-bottom">
            <thead>
            <tr class="d-flex">
                <th hidden="hidden" class="col-1">ID</th>
                <th class="col-2">NAZWA</th>
                <th class="col-2">OPIS</th>
                <th class="col-2">CENA</th>
                <th class="col-3">ILOŚĆ</th>
                <th class="col-2">AKCJE</th>
            </tr>
            </thead>
            <tbody class="text-color-lighter">
            {% for n in product %}
                <tr class="d-flex">

                    <td hidden="hidden" class="col-1">

                        {{ n.id }}

                    <td class="col-2">
                        {{ n.name }}
                    </td>
                    <td class="col-2">{{ n.description }}</td>
                    <td class="col-5">{{ n.price }}zł</td>
                    <td class="col-2 d-flex align-items-center justify-content-center flex-wrap">
                    <form action="" method="post">
                        {% csrf_token %}
                        <input hidden="hidden" type="text" name="product" value="{{ n.id }}">
                        <input type="submit" class="btn btn-danger rounded-0 text-light m-1" value="Dodaj do koszyka">

                    </form>



                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% endblock %}

templates/cart_detail.html
{% extends 'menu.html' %}
{% load static %}

{% block title %}Cart{% endblock %}


{% block content %}

<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">Cart</h3>
        </div>
        <div class="col d-flex justify-content-end mb-2 noPadding">
        </div>
    </div>
    <div class="schedules-content">
        <table class="table border-bottom">
            <thead>
            <tr class="d-flex">
                <th hidden="hidden" class="col-1">ID</th>
                <th class="col-2">PRODUKT</th>
                <th class="col-2">ILOŚĆ</th>
                <th class="col-2">USUŃ</th>
                <th class="col-3">CENA JEDNOSTKOWA</th>
                <th class="col-2">KWOTA</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                    <tr>
                        <td>{{ product.name }}</td>
                        <td>
                            <form action="{% url 'sushi:cart_add' product.id %}" method="post">
                                {{ item.update_quantity_form.quantity }}
                                {{ item.update_quantity_form.override }}
                                <input type="submit" value="Zmień">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td>

                          <form action="{% url "sushi:cart_remove" product.id %}" method="post">
                            <input type="submit" value="Usuń">
                            {% csrf_token %}
                          </form>
                        </td>

                        <td class="num">{{ item.price }} zł</td>
                        <td class="num">{{ item.total_price }} zł</td>
                    </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>Wartość całkowita</td>
                <td colspan="4"></td>
                <td class="num">{{ cart.get_total_price }} zł</td>
            </tr>
            </tbody>
        </table>
    <p class="text-right">
        <a href="{% url 'sushi:product_list' %}" class="button light">Kontynuuj zakupy</a>
        <a href="{% url 'sushi:order_create' %}" class="button">Do kasy</a>
    </p>

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}
    Home

{% endblock title %}

{% block content %}
Hi HI
    {% if user.is_authenticated %}



    {% endif %}

{% endblock %}

templates/hosomaki.html
{% extends 'menu.html' %}

{% block title %}Hosomaki{% endblock %}


{% block content %}

    {{  block.super }}


    {{  endblock }}
<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">Hosomaki</h3>
        </div>
        <div class="col d-flex justify-content-end mb-2 noPadding">
        </div>
    </div>
    <div class="schedules-content">
        <table class="table border-bottom">
            <thead>
            <tr class="d-flex">
                <th hidden="hidden" class="col-1">ID</th>
                <th class="col-2">NAZWA</th>
                <th class="col-2">OPIS</th>
                <th class="col-5">CENA</th>
                <th class="col-2">AKCJE</th>
            </tr>
            </thead>
            <tbody class="text-color-lighter">
            {% for n in hosomaki %}
                <tr class="d-flex">

                    <td hidden="hidden" class="col-1">

                        {{ n.id }}

                    <td class="col-2">
                        {{ n.name }}
                    </td>
                    <td class="col-2">{{ n.description }}</td>
                    <td class="col-5">{{ n.price }}zł</td>
                    <td class="col-2 d-flex align-items-center justify-content-center flex-wrap">
                    <form action="" method="post">
                        {% csrf_token %}
                        <input hidden="hidden" type="text" name="product" value="{{ n.id }}">
                        <input href="{% url 'sushi:AddToCart' %}" type="submit" class="btn btn-danger rounded-0 text-light m-1" value="Dodaj do koszyka">

                    </form>



                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    {% endblock %}

templates/menu.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Categories{% endblock %}

{% block content %}

<div class="btn-group btn-group-lg" role="group" aria-label="Large button group">
        <a href="{% url 'sushi:nigiri' %} " class="btn btn-outline-info" aria-current="page">Nigiri</a>
        <a href="{% url 'sushi:hosomaki' %} " class="btn btn-outline-info" aria-current="page">Hosomaki</a>
        <a href="{% url 'sushi:futomaki' %} " class="btn btn-outline-info" aria-current="page">Futomaki</a>
        <a href="{% url 'sushi:uramaki' %} " class="btn btn-outline-info" aria-current="page">Uramaki</a>
        <a href="{% url 'sushi:extras' %} " class="btn btn-outline-info" aria-current="page">Extras</a>
    </div>


{% endblock %}

templates/order_create.html
{% extends 'menu.html' %}
{%  load crispy_forms_tags %}

{% block title %}
    Order

{% endblock %}
{% block content %}
    <h1>Order</h1>
     <div class="order-info">
    <h3>Your order</h3>
    <ul>
      {% for item in cart %}
        <li>
          {{ item.quantity }}x {{ item.product.name }}
          <span>${{ item.total_price }}</span>
        </li>
      {% endfor %}
    </ul>
    <p>Total: ${{ cart.get_total_price }} zł</p>
  </div>

  <form method="post" class="order-form">
    {{ form|crispy }}
    <p><input type="submit" value="Place order"></p>
    {% csrf_token %}
  </form>
{% endblock %}

templates/order_created.html
{% extends 'menu.html' %}
{%  load crispy_forms_tags %}

{% block title %}
    Thank You

{% endblock %}
{% block content %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is<strong>{{ order.id }}</strong>.</p>

{% endblock %}

templates/partials/_menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">MySushi</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <a class="nav-link active" aria-current="page" href="{% url 'sushi:product_list' %}">Home</a>
        </li>
         <li class="nav-item">
         <a class="nav-link active" href="{% url 'sushi:product_list' %}">Menu</a>
        </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
         <a class="nav-link active" href="{% url 'logout' %}">Log Out {{ user.username }}</a>
        </li>
              <li class="nav-item">
         <a class="nav-link active" href="{% url 'sushi:cart_detail' %}">Cart</a>
        </li>
              {% else %}
        <li class="nav-item">
         <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
        </li>
              <li class="nav-item">
         <a class="nav-link active" aria-current="page" href="{% url 'sushi:signup' %}">Sign Up</a>
        </li>
          {% endif %}

            <li>
          <a class="nav-link active" aria-current="page">
              {% with total_items=cart|length %}
                  {% if total_items > 0 %}
                      Your cart:
                      <a href="{% url "sushi:cart_detail" %}">
                          {{ total_items }} item{{ total_items|pluralize }},
                          {{ cart.get_total_price }} zł
                      </a>
                  {% else %}
                      Your cart is empty.
                  {% endif %}
              {% endwith %}
          </a>
      </li>
      </ul>
    </div>
  </div>
</nav>

templates/product-list.html
{% extends 'base.html' %}


{% block title %}
    {% if category %}{{ category.name }}{% else %}Produkty{% endif %}
{% endblock %}

{% block content %}
    <div id="nav-sidebar">
    <h3>Kategorie</h3>
    <ul>
        <li {% if not category %} class="selected" {% endif %}>
            <a href="{% url 'sushi:product_list' %}">Wszystkie</a>
        </li>
        {% for c in categories %}
        <li>
            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
        {% endfor %}
    </ul>
    </div>
    <div id="content-main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Produkty{% endif %}</h1>
    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>{{ product.price }} zł
    </div>
    {% endfor %}
    </div>

{% endblock %}

templates/product-schedules.html
{% extends "base.html" %}

{% block title %}Futomaki{% endblock %}

{% block content %}

<div class="dashboard-content border-dashed p-3 m-4 view-height">

    <div class="row border-bottom border-3 p-1 m-1">
        <div class="col noPadding">
            <h3 class="color-header text-uppercase">Futomaki</h3>
        </div>
        <div class="col d-flex justify-content-end mb-2 noPadding">
        </div>
    </div>

    <div class="schedules-content">
        <table class="table border-bottom">
            <thead>
            <tr class="d-flex">
                <th class="col-1">ID</th>
                <th class="col-2">NAZWA</th>
                <th class="col-7">OPIS</th>
                <th class="col-2 center">AKCJE</th>
            </tr>
            </thead>
            <tbody class="text-color-lighter">
            {% for product in products_page.object_list %}
                <tr class="d-flex">
                    <th scope="row" class="col-1">{{ forloop.counter0|add:products_page.start_index }}</th>
                    <td class="col-2">
                        {{ product.name }}
                    </td>
                    <td class="col-7">{{ product.description }}</td>
                    <td class="col-2 d-flex align-items-center justify-content-center flex-wrap">
                        <a href="#"
                           class="btn btn-danger rounded-0 text-light m-1">Dodaj do koszyka</a>


                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if products_page.has_other_pages %}
            <div>
                {% if plan_page.has_previous %}
                    <a href="?page={{ products_page.previous_page_number }}">&lt poprzednia</a>
                {% endif %}

                {% for page_number in elided_page_range %}
                    {% if page_number != plan_page.paginator.ELLIPSIS %}
                        {% if products_page.number != 4 or page_number != 1 %}
                            {% if products_page.number != products_page.paginator.num_pages|add:"-3" or page_number != plan_page.paginator.num_pages %}
                                <a href="?page={{ page_number }}"> {{ page_number }} |</a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% endfor %}

                {% if plan_page.has_next %}
                    <a href="?page={{ products_page.next_page_number }}"> następna &gt</a>
                {% endif %}
            </div>
        {% endif %}

    </div>
</div>
{% endblock content %}

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {% if category %} {{ category.title }} {% else %}Produkty{% endif %}
{% endblock %}

{% block content %}
    <div class="product-detail">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">{{ product.price }} zł</p>
        <form action="{% url 'sushi:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Dodaj do koszyka">
        </form>
    {{ product.description|linebreaks }}
    </div>
{% endblock %}